### PR TITLE
Wither abilities, fixes #224

### LINKED ISSUE #224: You can't shoot wither skulls manually when possessing a Wither
Currently, when you possess a Wither, you can fully control its movement, but:
1. [ ] (a) You can't manually shoot Wither Skulls yet.
2. [ ] (b) Possessed Withers still shoot Wither Skulls of their own accord, ignoring the possessor.

As for shooting a Wither Skull, you should shoot a black Wither Skull if you aim near an entity when pressing the shoot key. If you are not aiming at an entity, you should instead shoot a blue Wither Skull.

To reproduce:
1. Download [this datapack](https://github.com/Ladysnake/Requiem/files/5826699/test_wither_skull.zip). It should show up as `file/test_wither_skull` in game.
2. Summon a Wither.
3. Possess the summoned Wither.
4. Try to shoot a Wither Skull. This currently fails.
5. Summon some non-undead creatures. Notice that the possessed Wither automatically shoots at the creatures without your consent.

Minecraft 1.16.4
Requiem 1.4.4
Pandemonium 1.4.4
Fabric API 0.29.3
Fabric loader 0.11.0

### PR DESCRIPTION
**Pull request by SekoiaTree**
This PR adds indirect and direct abilities to the wither (although it can only be possessed with datapacks). The blue wither skull is launched on indirect, the black on direct (range 20, like the mob, cooldown 40 on both).

Autocloser edit: Fixes #224

### CODE REVIEW

**Comment by SekoiaTree** [comment]
I'm not sure why the check failed: it builds for me, and the error isn't caused by my code

**Comment by Pyrofab** [comment]
Oh, the build fails because you did not update license headers. You need to run the `gradlew updateLicenses` task.

File: expansions/pandemonium/src/main/java/ladysnake/pandemonium/common/entity/ability/WitherSkullAbility.java [hunk 1]
```diff
@@ -0,0 +1,133 @@
...
+import net.minecraft.entity.boss.WitherEntity;
+import net.minecraft.entity.player.PlayerEntity;
+import net.minecraft.entity.projectile.WitherSkullEntity;
+import net.minecraft.util.math.MathHelper;
+import net.minecraft.util.math.Vec3d;
+
+import java.util.Random;
+
+public class WitherSkullAbility {
+    public static class BlueWitherSkullAbility extends IndirectAbilityBase<WitherEntity> {
```
Comment (Pyrofab) [inline expansions/pandemonium/src/main/java/ladysnake/pandemonium/common/entity/ability/WitherSkullAbility.java]: I would rather you make `WitherSkullAbility` extend `AbilityBase`, put all the common methods inside, then make both implementations extend `WitherSkullAbility`, with `BlueWitherSkullAbility` implementing `IndirectAbility` and `BlackWitherSkullAbility` implementing `DirectAbility`. This would reduce the amount of duplicated code quite a bit.

**Review by Pyrofab — CHANGES_REQUESTED** [review]
Thanks for the contribution ! I think we can improve the code a bit though.

File: expansions/pandemonium/src/main/java/ladysnake/pandemonium/common/entity/ability/WitherSkullAbility.java (hunk 1 above)
Comment (SekoiaTree) [reply expansions/pandemonium/src/main/java/ladysnake/pandemonium/common/entity/ability/WitherSkullAbility.java]: Alright, I'll make those changes

Comment (SekoiaTree) [reply expansions/pandemonium/src/main/java/ladysnake/pandemonium/common/entity/ability/WitherSkullAbility.java]: done

File: expansions/pandemonium/src/main/java/ladysnake/pandemonium/common/entity/ability/WitherSkullAbility.java [hunk 2]
```diff
@@ -0,0 +1,137 @@
...
+
+        @Override
+        public boolean trigger(LivingEntity target) {
+            int headIndex = RANDOM.nextInt(3);
+            double g = getHeadX(owner, headIndex);
+            double h = getHeadY(owner, headIndex);
+            double i = getHeadZ(owner, headIndex);
+            double j = target.getX() - g;
+            double k = target.getY() + (double)target.getStandingEyeHeight() * 0.5D - h;
+            double l = target.getZ() - i;
```
Comment (Pyrofab) [inline expansions/pandemonium/src/main/java/ladysnake/pandemonium/common/entity/ability/WitherSkullAbility.java]: Could you name all those variables ?

File: expansions/pandemonium/src/main/java/ladysnake/pandemonium/common/entity/ability/WitherSkullAbility.java [hunk 3]
```diff
@@ -0,0 +1,137 @@
...
+
+    private static WitherSkullEntity summonSkullWithTarget(WitherEntity owner, double j, double k, double l) {
+        int headIndex = RANDOM.nextInt(3);
+        double x = getHeadX(owner, headIndex);
+        double y = getHeadY(owner, headIndex);
+        double z = getHeadZ(owner, headIndex);
+        return summonSkullWithTarget(owner, x, y, z, j, k, l);
+    }
+
+    private static WitherSkullEntity summonSkullWithTarget(WitherEntity owner, double x, double y, double z, double j, double k, double l) {
```
Comment (Pyrofab) [inline expansions/pandemonium/src/main/java/ladysnake/pandemonium/common/entity/ability/WitherSkullAbility.java]: Could you name j, k, and l ?

File: expansions/pandemonium/src/main/java/ladysnake/pandemonium/common/entity/ability/WitherSkullAbility.java [hunk 4]
```diff
@@ -0,0 +1,137 @@
...
+        if (headIndex <= 0) {
+            return owner.getZ();
+        } else {
+            float f = (owner.bodyYaw + (float)(180 * (headIndex - 1))) * 0.017453292F;
+            float g = MathHelper.sin(f);
+            return owner.getZ() + (double)g * 1.3D;
+        }
+    }
+
+    private static WitherSkullEntity summonSkullWithTarget(WitherEntity owner, double j, double k, double l) {
```
Comment (Pyrofab) [inline expansions/pandemonium/src/main/java/ladysnake/pandemonium/common/entity/ability/WitherSkullAbility.java]: That method should be `protected` instead of `private static`. Also could you name j, k, and l ?

**Review by Pyrofab — CHANGES_REQUESTED** [review]

**Review by Pyrofab — APPROVED** [review]
Excellent, thank you very much !
